from __future__ import annotations

from paths import (
    ASSETS_DIR as PATH_ASSETS_DIR,
    DATA_DIR as PATH_DATA_DIR,
    MATCHES_DIR as PATH_MATCHES_DIR,
    PROJECT_ROOT as PATH_PROJECT_ROOT,
)

PROJECT_ROOT = str(PATH_PROJECT_ROOT)
ASSETS_DIR = str(PATH_ASSETS_DIR)
DATA_DIR = str(PATH_DATA_DIR)
MATCHES_DIR = str(PATH_MATCHES_DIR)
CSV_DATA_DIR = str(PATH_PROJECT_ROOT / "csv_data")
